services:
  keycloak-postgres:
    image: library/postgres:15-alpine3.19
    container_name: keycloak-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${KC_POSTGRES_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KC_POSTGRES_POSTGRES_PASSWORD}
      POSTGRES_DB: ${KC_POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - keycloack-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${KC_POSTGRES_POSTGRES_USER} -d ${KC_POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: 256M

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: ["start", "--db", "postgres", "--hostname-strict-https", "false", "--hostname-strict", "false", "--http-enabled", "true", "--import-realm"]
    environment:
      KC_DB_URL: "jdbc:postgresql://keycloak-postgres:5432/${KC_POSTGRES_DB}"
      KC_DB_USERNAME: ${KC_POSTGRES_POSTGRES_USER}
      KC_DB_PASSWORD: ${KC_POSTGRES_POSTGRES_PASSWORD}
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: ${KC_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY: true # https://github.com/keycloak/keycloak/issues/15255#issuecomment-1446166497
    volumes:
     - ./ObjectStore/:/ObjectStore/
    ports:
      - 8282:8080
    depends_on:
      keycloak-postgres:
        condition: service_healthy

volumes:
  keycloack-data:
